"""add_wrong_count_to_wrongnote

Revision ID: 02820a750686
Revises: d36265b34e19
Create Date: 2026-09-03 18:12:20.715507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02820a750686'
down_revision: Union[str, Sequence[str], None] = 'd36265b34e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WRONGNOTE', sa.Column('wrongCount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WRONGNOTE', 'wrongCount')
    # ### end Alembic commands ###
