"""add_is_favorited_to_wrongnote

Revision ID: 3aca6e71bca3
Revises: d420f36493ed
Create Date: 2026-09-01 20:29:59.158882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aca6e71bca3'
down_revision: Union[str, Sequence[str], None] = 'd420f36493ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WRONGNOTE', sa.Column('isFavorited', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WRONGNOTE', 'isFavorited')
    # ### end Alembic commands ###
