"""user_subjectid_not_null

Revision ID: 953a90357d89
Revises: bc2f51645b18
Create Date: 2026-08-13 17:15:49.023314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953a90357d89'
down_revision: Union[str, Sequence[str], None] = 'bc2f51645b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER', 'subjectId',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('USER', 'subjectId',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
