"""add supabase_uid to user, nullable subjectId

Revision ID: 9a423ea7e48c
Revises: c0b1684d857f
Create Date: 2026-08-12 16:37:04.675756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a423ea7e48c'
down_revision: Union[str, Sequence[str], None] = 'c0b1684d857f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('supabase_uid', sa.String(length=36), nullable=True))
    op.alter_column('USER', 'subjectId',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'USER', ['supabase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'USER', type_='unique')
    op.alter_column('USER', 'subjectId',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('USER', 'supabase_uid')
    # ### end Alembic commands ###
