"""add_updated_at_to_wrongnote

Revision ID: ac2abe32eb91
Revises: 02820a750686
Create Date: 2026-09-04 15:43:52.066102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2abe32eb91'
down_revision: Union[str, Sequence[str], None] = '02820a750686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WRONGNOTE', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WRONGNOTE', 'updatedAt')
    # ### end Alembic commands ###
