"""add self_diagnosis to anon_session

Revision ID: bc2f51645b18
Revises: 9a423ea7e48c
Create Date: 2026-08-13 17:03:06.078863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc2f51645b18'
down_revision: Union[str, Sequence[str], None] = '9a423ea7e48c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ANON_SESSION', sa.Column('self_diagnosis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ANON_SESSION', 'self_diagnosis')
    # ### end Alembic commands ###
