"""init tables

Revision ID: c0b1684d857f
Revises: 
Create Date: 2026-08-12 15:09:01.329135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b1684d857f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUBJECT',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subjectName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CONCEPT',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subjectId', sa.BigInteger(), nullable=False),
    sa.Column('conceptName', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['subjectId'], ['SUBJECT.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USER',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('subjectId', sa.BigInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subjectId'], ['SUBJECT.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ANON_SESSION',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sessionToken', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('mergedUserId', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['mergedUserId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sessionToken')
    )
    op.create_table('MASTERY',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('conceptId', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('sampleSize', sa.Integer(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conceptId'], ['CONCEPT.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('QUESTIONS',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subjectId', sa.BigInteger(), nullable=False),
    sa.Column('conceptId', sa.BigInteger(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('answerIndex', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trustScore', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conceptId'], ['CONCEPT.id'], ),
    sa.ForeignKeyConstraint(['subjectId'], ['SUBJECT.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ATTEMPT',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=True),
    sa.Column('anonSessionId', sa.BigInteger(), nullable=True),
    sa.Column('questionId', sa.BigInteger(), nullable=False),
    sa.Column('selectedIndex', sa.Integer(), nullable=False),
    sa.Column('isCorrect', sa.Boolean(), nullable=False),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anonSessionId'], ['ANON_SESSION.id'], ),
    sa.ForeignKeyConstraint(['questionId'], ['QUESTIONS.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WRONGNOTE',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('attemptId', sa.BigInteger(), nullable=False),
    sa.Column('conceptId', sa.BigInteger(), nullable=False),
    sa.Column('mistakeType', sa.Text(), nullable=True),
    sa.Column('userMemo', sa.Text(), nullable=True),
    sa.Column('reviewDueAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attemptId'], ['ATTEMPT.id'], ),
    sa.ForeignKeyConstraint(['conceptId'], ['CONCEPT.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WRONGNOTE')
    op.drop_table('ATTEMPT')
    op.drop_table('QUESTIONS')
    op.drop_table('MASTERY')
    op.drop_table('ANON_SESSION')
    op.drop_table('USER')
    op.drop_table('CONCEPT')
    op.drop_table('SUBJECT')
    # ### end Alembic commands ###
