"""add_home_fields_to_user_and_question_type

Revision ID: ccc6193aa22a
Revises: a1b2c3d4e5f6
Create Date: 2026-08-23 17:47:49.127309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc6193aa22a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QUESTIONS', sa.Column('questionType', sa.String(length=20), nullable=False, server_default='GENERATED'))
    op.add_column('USER', sa.Column('examName', sa.String(length=100), nullable=True))
    op.add_column('USER', sa.Column('examDate', sa.Date(), nullable=True))
    op.add_column('USER', sa.Column('streakCount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('USER', sa.Column('lastStudiedAt', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'lastStudiedAt')
    op.drop_column('USER', 'streakCount')
    op.drop_column('USER', 'examDate')
    op.drop_column('USER', 'examName')
    op.drop_column('QUESTIONS', 'questionType')
    # ### end Alembic commands ###
