"""refactor_wrongnote_replace_attemptid_with_questionid

Revision ID: d36265b34e19
Revises: 3aca6e71bca3
Create Date: 2026-09-03 17:35:33.630064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36265b34e19'
down_revision: Union[str, Sequence[str], None] = '3aca6e71bca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # attemptId → questionId 구조 변경. 기존 행은 questionId를 채울 수 없으므로 먼저 삭제.
    op.execute('DELETE FROM "WRONGNOTE"')
    op.drop_constraint(op.f('WRONGNOTE_attemptId_fkey'), 'WRONGNOTE', type_='foreignkey')
    op.drop_column('WRONGNOTE', 'attemptId')
    op.add_column('WRONGNOTE', sa.Column('questionId', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('uq_wrongnote_user_question', 'WRONGNOTE', ['userId', 'questionId'])
    op.create_foreign_key(None, 'WRONGNOTE', 'QUESTIONS', ['questionId'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WRONGNOTE', sa.Column('attemptId', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'WRONGNOTE', type_='foreignkey')
    op.create_foreign_key(op.f('WRONGNOTE_attemptId_fkey'), 'WRONGNOTE', 'ATTEMPT', ['attemptId'], ['id'])
    op.drop_constraint('uq_wrongnote_user_question', 'WRONGNOTE', type_='unique')
    op.drop_column('WRONGNOTE', 'questionId')
    # ### end Alembic commands ###
